services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r render_requirements.txt
    startCommand: python3 render_no_auth_bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_API_ID
        value: "26886585"
      - key: TELEGRAM_API_HASH
        value: "166e3719a0d93c12bf76af43fe91425f"
      - key: BOT_TOKEN
        value: "8189087426:AAF2XtTEwDRbwvWny-Hi2BPz_0ZeJHh9DEc"
      - key: ADMIN_IDS
        value: "6395626140,7766810783"
      - key: SOURCE_GROUP
        value: "https://t.me/pereizdvyshneve"
      - key: TARGET_CHANNEL
        value: "@kryuvysh"
      - key: PORT
        value: "5000"